language: python

python:
  # - "3.4"
  # - "3.3"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install

script: cd example && python manage.py test && codecov
