dist: xenial  # for Python3.7+
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django18,py27-django19,py27-django10,py27-django11
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20,py36-django21,py36-django22
    - python: 3.7
      env: TOXENV=py37-django20,py37-django21,py37-django22

install:
  - pip install codecov tox

script: tox && codecov
